//
//  ViewController.swift
//  login
//
//  Created by exportkit on 2021.
//  Copyright (c)  exportkit. All rights reserved.
//  Generated by Export Kit v128
//
	
import UIKit
	
class ViewController: UIViewController {
	
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }
	
}
